# Generated by Django 6.0.3 on 2026-03-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
                ('total_projects', models.IntegerField(default=0)),
                ('approved_projects', models.IntegerField(default=0)),
                ('pending_projects', models.IntegerField(default=0)),
                ('rejected_projects', models.IntegerField(default=0)),
                ('trending_technologies', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
